repos:
  - repo: local
    hooks:
      - id: format-check
        name: ruff format check
        entry: uv run ruff format --check
        language: system
        types: [python]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.29
    hooks:
      - id: uv-lock
